### ISSUE TITLE
MiniZinc IDE sometimes stops outputting solutions before reaching the optimal one

### ISSUE THREAD

**Issue by Zero3** [MiniZinc/MiniZincIDE#10]
I've been having some weird issues with my MiniZinc model, and have managed to track down one of the problems, which I believe is caused by a bug in MiniZinc IDE.

Consider the following simple model of selecting a number of items such that you obtain the maximum stat1:

```
% Items and their stats
set of int: Items = 1..187;
set of int: Stats = 1..2;
array[Items, Stats] of float: itemStats = [|0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |380.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |150.0, 0.0 |0.0, 15.0 |0.0, 40.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |80.0, 0.0 |80.0, 0.0 |60.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 30.0 |0.0, 30.0 |0.0, 30.0 |0.0, 30.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |400.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |400.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |400.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |500.0, 0.0 |150.0, 0.0 |0.0, 40.0 |200.0, 0.0 |200.0, 0.0 |500.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |225.0, 0.0 |0.0, 0.0 |650.0, 0.0 |0.0, 25.0 |0.0, 65.0 |0.0, 60.0 |300.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |200.0, 0.0 |0.0, 0.0 |0.0, 30.0 |0.0, 30.0 |150.0, 0.0 |500.0, 0.0 |300.0, 50.0 |0.0, 0.0 |200.0, 0.0 |500.0, 0.0 |200.0, 0.0 |500.0, 50.0 |0.0, 0.0 |0.0, 0.0 |300.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 100.0 |0.0, 0.0 |250.0, 0.0 |0.0, 40.0 |850.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |175.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |500.0, 0.0 |200.0, 0.0 |0.0, 0.0 |0.0, 90.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |400.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |200.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |500.0, 60.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |300.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 45.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |400.0, 0.0 |0.0, 30.0 |200.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |75.0, 0.0 |0.0, 0.0 |450.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 60.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |500.0, 50.0 |450.0, 0.0 |300.0, 0.0 |500.0, 0.0 |200.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0 |0.0, 0.0|];

% Item selection variables
set of int: Selections = 1..6;
array[Selections] of var Items: selections;

% Helper function to retrieve the resulting sum of a specific stat
function var float: stat(int: stat) = sum (s in Selections) (itemStats[selections[s], stat]);

% Solve
var float: totalStat1 = stat(1);
var float: totalStat2 = stat(2);
solve maximize totalStat1;

% Output
output ["Selected item \(selections[s]): \(itemStats[selections[s], 1]) stat1 + \(itemStats[selections[s], 2]) stat2\n" | s in Selections]
  ++ ["Total stat1: \(totalStat1)\n"]
  ++ ["Total stat2: \(totalStat2)\n"];
```

When run with the bundled Gecode solver, I get the following output:

````
[...]
----------
Selected item 58: 400.0 stat1 + 0.0 stat2
Selected item 118: 850.0 stat1 + 0.0 stat2
Selected item 118: 850.0 stat1 + 0.0 stat2
Selected item 118: 850.0 stat1 + 0.0 stat2
Selected item 118: 850.0 stat1 + 0.0 stat2
Selected item 118: 850.0 stat1 + 0.0 stat2
Total stat1: 4650.0
Total stat2: 0.0
----------
Finished in 110msec
````

Notice that the result is not optimal. If I compile the model using the MiniZinc -> Compile menu, save the resuls as an .fzn file and run it, I get the optimal result:

````
[...]
----------
selections = array1d(1..6, [118, 118, 118, 118, 118, 118]);
totalStat1 = 5100.0;
totalStat2 = -0.0;
----------
==========
````

Weirdly, a number of different changes that should not affect the result causes MiniZinc IDE to correctly find the optimal solution:

* Using `sum (s in Selections) (itemStats[selections[s], stat])` directly in `totalStat1` or `totalStat2` instead of calling `stat(1)` or `stat(2)`

* Removing any of the last 2 output lists

* Removing all other items than item 58 and item 118 from the item stats table

* ...

Another issue that may or may not be connected is triggered by removing the first output list:

````
Compiling debug.mzn
Running debug.mzn
MiniZinc: type error: undefined identifier `Items'
C:/Users/Zero3/AppData/Local/Temp/MiniZinc IDE-eedd3E/debug.ozn:3
Finished in 128msec
````

I'm at a loss here :(

**Comment by guidotack** [comment]
I've received several similar reports but so far have not been able to reproduce the behaviour. Please let me know which operating system and which exact version of the IDE (version number and whether t's the bundled binary) you are using.

**Comment by guidotack** [comment]
The second issue you mentioned was in fact a bug. A fix will be part of the upcoming 2.0.13 release.

**Comment by Zero3** [comment]
I'm using the MiniZinc IDE 2.0.12 bundle on Windows 7 x64, fully patch except for the Windows 10 spyware/adware/nagware updates.

I'll be happy to help debugging. Let me know if there is anything I can do!

**Comment by Zero3** [comment]
I've peeked around in the source code of MiniZinc IDE and performed a couple of experiments. I made the following observations:

1) If I manually run the same processes that the IDE runs to solve the model, with the same arguments and IDE-generated .fzn and .ozn files (which I captured from my temp folder), the output of solns2out.exe at the end correctly contains the optimal solution.

2) The bad output from a solve in the IDE is actually the first X suboptimal solutions of the full output of solns2out.exe.

3) If "Print all solutions" is disabled in the IDE, the output correctly contains (only) the optimal solution.

This leads me to believe that this bug is actually the IDE not reading the full contents of the stdout of solns2out.exe. Maybe this is caused by the stdout being buffered and not flushed by neither solns2out.exe nor the IDE, or maybe this is a race condition of some kind. The following thread seems highly relevant:

https://forum.qt.io/topic/1316/qprocess-working-qiodevice-unbuffered-or-adjustable-buffersize-for-faster-access-to-stdout

I hope this helps you fix the issue.

**Comment by guidotack** [comment]
This was indeed a buffering problem (I already suspected that, we've had problems with this in the past). The QProcess seems to behave slightly differently on Windows, but I finally found a machine where I could reproduce the problem.  Hope it's fixed now for you too.

**Comment by Zero3** [comment]
Just downloaded 2.0.13, and it appears to work now! Thanks :).

**Comment by Zero3** [comment]
It appears like this is not completely fixed after all. I just ran into another model that fails with this bug under 2.0.13. I will try to extract a minimal working example of the bug when I get the time.

(I can't reopen this issue, so you will have to do that @guidotack)

**Comment by Zero3** [comment]
@guidotack FYI, this issue is still present. Not sure if you saw my previous comment about this issue being closed.
